package pe.edu.unmsm.sisgiste.entity;
// Generated 03-feb-2019 18:44:56 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Incidencia generated by hbm2java
 */
@Entity
@Table(name = "incidencia", catalog = "modelogeneralfisi")
public class Incidencia implements java.io.Serializable {

	private Integer idIncidencia;
	private LugarIncidencia lugarIncidencia;
	private Tecnico tecnicoByTecnicoIdTecnicoRecepcionista;
	private Tecnico tecnicoByTecnicoIdTecnicoSolucionador;
	private TipoEquipo tipoEquipo;
	private String incidenciaUsuario;
	private String sbn;
	private String problema;
	private String incidenciaDescripcionSolucion;
	private Date incidenciaFecha;
	private Date incidenciaHoraInicio;
	private Date incidenciaHoraFin;
	private String estado;

	public Incidencia() {
	}

	public Incidencia(LugarIncidencia lugarIncidencia, Tecnico tecnicoByTecnicoIdTecnicoRecepcionista,
			Date incidenciaFecha, Date incidenciaHoraInicio, String estado) {
		this.lugarIncidencia = lugarIncidencia;
		this.tecnicoByTecnicoIdTecnicoRecepcionista = tecnicoByTecnicoIdTecnicoRecepcionista;
		this.incidenciaFecha = incidenciaFecha;
		this.incidenciaHoraInicio = incidenciaHoraInicio;
		this.estado = estado;
	}

	public Incidencia(LugarIncidencia lugarIncidencia, Tecnico tecnicoByTecnicoIdTecnicoRecepcionista,
			Tecnico tecnicoByTecnicoIdTecnicoSolucionador, TipoEquipo tipoEquipo, String incidenciaUsuario, String sbn,
			String problema, String incidenciaDescripcionSolucion, Date incidenciaFecha, Date incidenciaHoraInicio,
			Date incidenciaHoraFin, String estado) {
		this.lugarIncidencia = lugarIncidencia;
		this.tecnicoByTecnicoIdTecnicoRecepcionista = tecnicoByTecnicoIdTecnicoRecepcionista;
		this.tecnicoByTecnicoIdTecnicoSolucionador = tecnicoByTecnicoIdTecnicoSolucionador;
		this.tipoEquipo = tipoEquipo;
		this.incidenciaUsuario = incidenciaUsuario;
		this.sbn = sbn;
		this.problema = problema;
		this.incidenciaDescripcionSolucion = incidenciaDescripcionSolucion;
		this.incidenciaFecha = incidenciaFecha;
		this.incidenciaHoraInicio = incidenciaHoraInicio;
		this.incidenciaHoraFin = incidenciaHoraFin;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_INCIDENCIA", unique = true, nullable = false)
	public Integer getIdIncidencia() {
		return this.idIncidencia;
	}

	public void setIdIncidencia(Integer idIncidencia) {
		this.idIncidencia = idIncidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LUGAR_INCIDENCIA_ID", nullable = false)
	public LugarIncidencia getLugarIncidencia() {
		return this.lugarIncidencia;
	}

	public void setLugarIncidencia(LugarIncidencia lugarIncidencia) {
		this.lugarIncidencia = lugarIncidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TECNICO_ID_TECNICO_RECEPCIONISTA", nullable = false)
	public Tecnico getTecnicoByTecnicoIdTecnicoRecepcionista() {
		return this.tecnicoByTecnicoIdTecnicoRecepcionista;
	}

	public void setTecnicoByTecnicoIdTecnicoRecepcionista(Tecnico tecnicoByTecnicoIdTecnicoRecepcionista) {
		this.tecnicoByTecnicoIdTecnicoRecepcionista = tecnicoByTecnicoIdTecnicoRecepcionista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TECNICO_ID_TECNICO_SOLUCIONADOR")
	public Tecnico getTecnicoByTecnicoIdTecnicoSolucionador() {
		return this.tecnicoByTecnicoIdTecnicoSolucionador;
	}

	public void setTecnicoByTecnicoIdTecnicoSolucionador(Tecnico tecnicoByTecnicoIdTecnicoSolucionador) {
		this.tecnicoByTecnicoIdTecnicoSolucionador = tecnicoByTecnicoIdTecnicoSolucionador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_EQUIPO_ID")
	public TipoEquipo getTipoEquipo() {
		return this.tipoEquipo;
	}

	public void setTipoEquipo(TipoEquipo tipoEquipo) {
		this.tipoEquipo = tipoEquipo;
	}

	@Column(name = "INCIDENCIA_USUARIO", length = 45)
	public String getIncidenciaUsuario() {
		return this.incidenciaUsuario;
	}

	public void setIncidenciaUsuario(String incidenciaUsuario) {
		this.incidenciaUsuario = incidenciaUsuario;
	}

	@Column(name = "SBN", length = 45)
	public String getSbn() {
		return this.sbn;
	}

	public void setSbn(String sbn) {
		this.sbn = sbn;
	}

	@Column(name = "PROBLEMA", length = 300)
	public String getProblema() {
		return this.problema;
	}

	public void setProblema(String problema) {
		this.problema = problema;
	}

	@Column(name = "INCIDENCIA_DESCRIPCION_SOLUCION", length = 200)
	public String getIncidenciaDescripcionSolucion() {
		return this.incidenciaDescripcionSolucion;
	}

	public void setIncidenciaDescripcionSolucion(String incidenciaDescripcionSolucion) {
		this.incidenciaDescripcionSolucion = incidenciaDescripcionSolucion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INCIDENCIA_FECHA", nullable = false, length = 10)
	public Date getIncidenciaFecha() {
		return this.incidenciaFecha;
	}

	public void setIncidenciaFecha(Date incidenciaFecha) {
		this.incidenciaFecha = incidenciaFecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "INCIDENCIA_HORA_INICIO", nullable = false, length = 8)
	public Date getIncidenciaHoraInicio() {
		return this.incidenciaHoraInicio;
	}

	public void setIncidenciaHoraInicio(Date incidenciaHoraInicio) {
		this.incidenciaHoraInicio = incidenciaHoraInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "INCIDENCIA_HORA_FIN", length = 8)
	public Date getIncidenciaHoraFin() {
		return this.incidenciaHoraFin;
	}

	public void setIncidenciaHoraFin(Date incidenciaHoraFin) {
		this.incidenciaHoraFin = incidenciaHoraFin;
	}

	@Column(name = "ESTADO", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
