package pe.edu.unmsm.sisgiste.entity;
// Generated 03-feb-2019 18:44:56 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LugarIncidencia generated by hbm2java
 */
@Entity
@Table(name = "lugar_incidencia", catalog = "modelogeneralfisi")
public class LugarIncidencia implements java.io.Serializable {

	private Integer idLugarIncidencia;
	private TipoLugarIncidencia tipoLugarIncidencia;
	private String lugarIncidenciaNombre;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public LugarIncidencia() {
	}

	public LugarIncidencia(String lugarIncidenciaNombre) {
		this.lugarIncidenciaNombre = lugarIncidenciaNombre;
	}

	public LugarIncidencia(TipoLugarIncidencia tipoLugarIncidencia, String lugarIncidenciaNombre,
			Set<Incidencia> incidencias) {
		this.tipoLugarIncidencia = tipoLugarIncidencia;
		this.lugarIncidenciaNombre = lugarIncidenciaNombre;
		this.incidencias = incidencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LUGAR_INCIDENCIA", unique = true, nullable = false)
	public Integer getIdLugarIncidencia() {
		return this.idLugarIncidencia;
	}

	public void setIdLugarIncidencia(Integer idLugarIncidencia) {
		this.idLugarIncidencia = idLugarIncidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_LUGAR_INCIDENCIA_ID")
	public TipoLugarIncidencia getTipoLugarIncidencia() {
		return this.tipoLugarIncidencia;
	}

	public void setTipoLugarIncidencia(TipoLugarIncidencia tipoLugarIncidencia) {
		this.tipoLugarIncidencia = tipoLugarIncidencia;
	}

	@Column(name = "LUGAR_INCIDENCIA_NOMBRE", nullable = false, length = 70)
	public String getLugarIncidenciaNombre() {
		return this.lugarIncidenciaNombre;
	}

	public void setLugarIncidenciaNombre(String lugarIncidenciaNombre) {
		this.lugarIncidenciaNombre = lugarIncidenciaNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugarIncidencia")
	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

}
