package pe.edu.unmsm.sisgiste.entity;
// Generated 03-feb-2019 18:44:56 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEquipo generated by hbm2java
 */
@Entity
@Table(name = "tipo_equipo", catalog = "modelogeneralfisi")
public class TipoEquipo implements java.io.Serializable {

	private Integer idTipoEqupo;
	private String equipoDsecripcion;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public TipoEquipo() {
	}

	public TipoEquipo(String equipoDsecripcion) {
		this.equipoDsecripcion = equipoDsecripcion;
	}

	public TipoEquipo(String equipoDsecripcion, Set<Incidencia> incidencias) {
		this.equipoDsecripcion = equipoDsecripcion;
		this.incidencias = incidencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TIPO_EQUPO", unique = true, nullable = false)
	public Integer getIdTipoEqupo() {
		return this.idTipoEqupo;
	}

	public void setIdTipoEqupo(Integer idTipoEqupo) {
		this.idTipoEqupo = idTipoEqupo;
	}

	@Column(name = "EQUIPO_DSECRIPCION", nullable = false, length = 45)
	public String getEquipoDsecripcion() {
		return this.equipoDsecripcion;
	}

	public void setEquipoDsecripcion(String equipoDsecripcion) {
		this.equipoDsecripcion = equipoDsecripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEquipo")
	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

}
