package pe.edu.unmsm.sisgiste.entity;
// Generated 03-feb-2019 18:44:56 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "modelogeneralfisi")
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private Persona persona;
	private Sistema sistema;
	private TipoUsuario tipoUsuario;
	private Integer usuarioActivo;

	public Usuario() {
	}

	public Usuario(Persona persona, Sistema sistema, TipoUsuario tipoUsuario) {
		this.persona = persona;
		this.sistema = sistema;
		this.tipoUsuario = tipoUsuario;
	}

	public Usuario(Persona persona, Sistema sistema, TipoUsuario tipoUsuario, Integer usuarioActivo) {
		this.persona = persona;
		this.sistema = sistema;
		this.tipoUsuario = tipoUsuario;
		this.usuarioActivo = usuarioActivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_USUARIO", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PERSONA_ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SISTEMA_ID_SISTEMA", nullable = false)
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TIPO_USUARIO_IDTIPO_USUARIO", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "USUARIO_ACTIVO")
	public Integer getUsuarioActivo() {
		return this.usuarioActivo;
	}

	public void setUsuarioActivo(Integer usuarioActivo) {
		this.usuarioActivo = usuarioActivo;
	}

}
